name: Build and Push Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_KEY }}'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: "vibradev-dev"

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and push Docker image
        env: 
          IMAGE: us-central1-docker.pkg.dev/vibradev-dev/dev/fastapi-app
          TAG: ${{ github.run_number }}
        run: |
          docker build -t $IMAGE:$TAG -t $IMAGE:latest .
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest

      - name: Install yq
        run: |
          sudo apt-get update && sudo apt-get install -y jq python3-pip
          pip3 install yq

      - name: Bump version in Dockerfile
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          yq -i ".version = \"${TAG}\" | .appVersion = \"${TAG}\"" fastapi-chart/Chart.yaml
          yq -i ".image.tag = \"${TAG}\"" fastapi-chart/values.yaml
      
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Bump version to ${TAG}"
          file_pattern: |
            fastapi-chart/Chart.yaml
            fastapi-chart/values.yaml
          branch: main